### ISSUE TITLE
Is it possible to enable disable instance animation playback? 

### ISSUE THREAD

**Issue by crookedbard** [lucidspriter/SpriterPlusPlus#25]
when I create an entity instance with play() function it automatically sets all animations to have a playback.
If I call playOnce then all animations won't have playback. How to dynamically manage such option for the same instance?

**Comment by lucidspriter** [comment]
Could you show a code example of what you're doing?   I'm not sure exactly what you mean.

**Comment by crookedbard** [comment]
I have Spriter animation file that contains 2 types of animations: one type is continues animation (walk, run) other type - played once (attack, being hit).

So I create an animation node and 1 entityInstnace with "play" function.
On animations walk & run everything works great. Animation loops continuously.
But now with other animations I try to catch animation end time to stop it precisely when the animation is finished. 

```
auto scml = cocos2d::FileUtils::getInstance()->fullPathForFilename("char/plr1/Animations.scml");
    _plrAnimationNode = Spriter2dX::AnimationNode::create(scml, Spriter2dX::AnimationNode::cacheLoader());
    _plrEntityInstance = _plrAnimationNode->play("Player sprite");
    _plrEntityInstance->setCurrentAnimation("Front - Idle");
//    _plrEntityInstance->animationJustFinished(); // it never finishes because animation always loops
//    _plrEntityInstance->animationJustLooped(); // it does not hit precicely on animation end, but when new animation begins
    _plrEntityInstance->pausePlayback(); //animation stops instantely
```

How to get a callback when animation is finished?

**Comment by lucidspriter** [comment]
It looks like you're using [Spriter2dx](https://github.com/jeremyjh/Spriter2dX).  Have you tried posting this issue there?

**Comment by crookedbard** [comment]
whoops, so sorry wrong hub :D

**Comment by lucidspriter** [comment]
no worries :)
